<?php
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class MsDosen extends Model
{
    protected $table = 'peg.ms_pegawai';
    public $timestamps = false;
    public $autoincrement = false;
    public $incrementing  = false;
    protected $primaryKey = "nip";
    protected $fillable = [
        'nip',
        'kodeunit',
        'nama',
        'gelardepan',
        'gelarbelakang',
        'sex',
        'tmplahir',
        'tgllahir',
        'goldarah',
        'alamat',
        'kodepos',
        'telp',
        'telp2',
        'hp',
        'hp2',
        'email',
        'email2',
        'noktp',
        'npwp',
        'kelurahan',
        'kecamatan',
        'tinggibadan',
        'beratbadan',
        'cacattubuh',
        'hobi',
        'noskkelbaik',
        'tglskkelbaik',
        'pejabatskkelbaik',
        'nosksehat',
        'tglsksehat',
        'pejabatsksehat',
        'nidn',
        'nidnnew',
        'kodependapatan',
        'kodekota',
        'statustetap',
        'kodeagama',
        'kodewn',
        'tipepeg',
        'statuspeg',
        'statusnikah',
        'kodepekrjstrisuami',
        'namaistrisuami',
        'namaanak1',
        'namaanak2',
        'tgllahiristrisuami',
        'tgllahiranak1',
        'tgllahiranak2',
        'jeniskelaministrisuami',
        'jeniskelaminanak1',
        'jeniskelaminanak2',
        'norekening',
        'namabank',
        'namacabang',
        'catatankhusus',
        'rekatasnama',
        'nik',
        't_updateuser',
        't_updateip',
        't_updatetime',
        't_updateact',
        'nilai_toefl',
        'jabstruktural',
        'jabakademik',
        'penddosen',
    ];
}
